tasks:
  - init: echo 'C++ Initialisation - Run g++  hello.cpp -o main.out to build and ./main.out to run.' # runs during prebuild
    command: echo 'build main.cpp' && g++  hello.cpp -o main.out

ports:
  - port: 3000
    onOpen: open-preview
