
tasks:
  - init: echo 'Press run button on main.cpp to build and run or use command line to build and run.' # runs during prebuild
    command: g++ main -o main.out && ./main

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - formulahendry.code-runner